/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.habitlab;

@com.tns.JavaScriptImplementation(javaScriptFile = "./services/AccessibilityService.js")
public class AccessibilityService extends android.accessibilityservice.AccessibilityService implements com.tns.NativeScriptHashCodeProvider {
	public AccessibilityService(){
		super();
		com.tns.Runtime.initInstance(this);
	}

	public void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		com.tns.Runtime.callJSMethod(this, "onAccessibilityEvent", void.class, args);
	}

	public void onInterrupt()  {
		java.lang.Object[] args = null;
		com.tns.Runtime.callJSMethod(this, "onInterrupt", void.class, args);
	}

	protected void onServiceConnected()  {
		java.lang.Object[] args = null;
		com.tns.Runtime.callJSMethod(this, "onServiceConnected", void.class, args);
	}

	public boolean equals__super(java.lang.Object other) {
		return super.equals(other);
	}

	public int hashCode__super() {
		return super.hashCode();
	}

}
